image: node:latest
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install --cache-folder .yarn

cache:
  paths:
    - node_modules/
    - .yarn

build:
  stage: build
  artifacts:
    paths:
      - lib/
      - creevey-*.tgz
  script:
    - yarn lint
    - yarn build
    - yarn pack
unit:
  script:
    - yarn test:unit

# NOTE: This job failed by timeout
# e2e:
#   script:
#     - yarn test:e2e

ui:
  stage: test
  services:
    - selenoid/chrome
    - selenoid/firefox
  dependencies:
    - build
  artifacts:
    when: always
    paths:
      - report/
  script:
    - yarn start:storybook &
    - yarn creevey --config .creevey/gitlab.config.ts
