image: node:latest
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install --cache-folder .yarn

cache:
  paths:
    - node_modules/
    - .yarn

lint:
  script:
    - yarn lint

build:
  artifacts:
    paths:
      - creevey-*.tgz
  script:
    - yarn build
    - yarn pack
# e2e:
#   script:
#     - yarn test:e2e

tests:
  # artifacts:
  #   paths:
  #     - report/
  script:
    - yarn test:unit
# NOTE: Disable test until allow use standalone binary for selenoid
#    - yarn start:storybook &
#    - yarn creevey
