version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: circleci/node:12.18.4

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build
      - run:
          name: Pack
          command: yarn pack -f creevey.tgz
      - persist_to_workspace:
          root: lib
          paths:
            - "*"
      - store_artifacts:
          path: creevey.tgz

  e2e:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: E2E tests
          command: yarn test:e2e

  tests:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - attach_workspace:
          at: lib
      - run:
          name: Git LFS (install Git Large File Storage)
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install
      - checkout
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Unit tests
          command: yarn test:unit
      - run:
          name: Storybook Start
          command: yarn start:storybook
          background: true
      - run:
          name: Screenshot tests
          command: yarn creevey
      - store_artifacts:
          path: report

workflows:
  tests:
    jobs:
      - build
      - e2e
      - tests
