name: build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: pack
        run: yarn pack
      - uses: actions/upload-artifact@v2
        with:
          name: creevey
          path: creevey-*.tgz
