name: Build and Test
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: pack
        run: yarn pack
      - uses: actions/upload-artifact@v2
        with:
          name: creevey
          path: creevey-*.tgz
  e2e-fixtures:
    name: Storybook Fixtures E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn
      - name: tests
        run: yarn test:e2e --grep Fixtures
  e2e-storybook:
    name: Storybook Official E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: creevey
    steps:
      - name: Checkout Creevey
        uses: actions/checkout@v2
        with:
          path: creevey
      - name: Checkout Storybook
        uses: actions/checkout@v2
        with:
          repository: https://github.com/creevey/storybook.git
          ref: creevey
          path: storybook
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn
      - name: bootstrap
        run: yarn bootstrap:storybook
      - name: tests
        run: yarn test:e2e --grep Official
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: checkout lfs
        run: git lfs checkout
      - name: install
        run: yarn
      - name: unit tests
        run: yarn test:unit
      - name: storybook
        run: yarn start:storybook &
      - name: creevey
        run: yarn creevey
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: report/
